### PR TITLE
update replay scripts

### PR DESCRIPTION
**Pull request by jackzhy96**

### CODE REVIEW

**Review by jabarragann — CHANGES_REQUESTED** [review]
discussed changes

**Comment by jackzhy96** [comment]
The changes have been resolved and the grasping code is pushed as well.

**Comment by jackzhy96** [comment]
Hi Juan,
I have double-checked the changes you request. I don't think it will break anything and it is actually a fix since the old code is missing some inputs. 

In addition, I have just managed to solve the previous problem and enable the active grasping algorithm (AKA, given needle pose and let the PSM actively move to pick the needle up).

**Review by jackzhy96 — COMMENTED** [review]
Would you mind letting me know where I need to modify? Is it because the modifications on line 240-242 and line 245-247 in "record_replay_pipeline.py" for resetting PSM? If so, I may remove them. Otherwise, the modification for "run_record" function is required since the function should have corresponding inputs to execute.

**Review by jabarragann — APPROVED** [review]

**Pull request merged**
